import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useI18n } from '@/i18n'
import { useAuthContext } from '@/contexts/AuthContext'
import { useSocketContext } from '@/contexts/SocketContext'
import { useAuthFlow } from '@/hooks/useAuthFlow'
import { Button } from '@/components/atoms/Button'
import { PinInput } from '@/components/atoms/PinInput'
import { Typography } from '@/components/atoms/Typography'
import logoBig from '@/assets/logo-big.png'
import { Routes } from '@/routes'

export type AuthMode = 'select' | 'owner-pin'

export function AuthPage() {
  const [pin, setPin] = useState('')
  const [mode, setMode] = useState<AuthMode>('select')
  const [randomOwnerPin, setRandomOwnerPin] = useState<string | null>(null)
  const navigate = useNavigate()
  const { i18nText } = useI18n()
  const { login, setOwner } = useAuthContext()
  const { socket, connected } = useSocketContext()

  const { submitPin, error, loading, clearError } = useAuthFlow({
    socket,
    connected,
    setOwner,
    login,
  })

  // Fetch random owner PIN if generated by server (plug-and-play mode)
  useEffect(() => {
    fetch('/api/owner-pin')
      .then(res => res.json())
      .then(data => {
        if (data.isRandom && data.pin) {
          setRandomOwnerPin(data.pin)
        }
      })
      .catch(() => {
        // Silently fail — PIN entry still works manually
      })
  }, [])

  const handleOwnerClick = () => {
    setMode('owner-pin')
    setPin('')
    clearError()
  }

  const handleRefereeClick = () => {
    login('referee')
    navigate(Routes.DASHBOARD_REFEREE)
  }

  const handleSpectatorClick = () => {
    login('viewer')
    navigate(Routes.DASHBOARD_SPECTATOR)
  }

  const handlePinChange = (value: string) => {
    setPin(value)
    if (value.length >= 5 && value.length <= 8) {
      clearError()
    }
  }

  const handlePinSubmit = () => {
    submitPin(pin)
  }

  /** Translate error codes from useAuthFlow to human-readable messages */
  const translateAuthError = (code: string): string => {
    const map: Record<string, string> = {
      INVALID_OWNER_PIN: i18nText('errorAuthInvalidPin'),
      INVALID_OWNER_PIN_FORMAT: i18nText('errorAuthInvalidPinFormat'),
      CONNECTION_ERROR: i18nText('errorAuthConnectionError'),
      VALIDATION_ERROR: i18nText('errorAuthValidationError'),
    }
    return map[code] || code
  }

  const handleBack = () => {
    setMode('select')
    setPin('')
    clearError()
  }

  return (
    <div className="flex flex-col items-center justify-center min-h-dvh bg-surface gap-8 p-4">
      <div className="flex flex-col items-center gap-4">
        <img src={logoBig} alt="RallyOS" className="w-32 h-auto mb-2" />
        <Typography variant="title">
          {mode === 'select' ? i18nText('authSelectRole') : i18nText('authEnterOwnerPin')}
        </Typography>
      </div>

      {mode === 'select' ? (
        // Selection Mode - 3 buttons
        <div className="flex flex-col gap-4 w-full max-w-sm">
          <Button
            variant="primary"
            size="lg"
            onClick={handleOwnerClick}
            disabled={loading}
            animate={false}
          >
            {i18nText('authRoleOwner')}
          </Button>
          <Button
            variant="secondary"
            size="lg"
            onClick={handleRefereeClick}
            disabled={loading}
            animate={false}
          >
            {i18nText('authRoleReferee')}
          </Button>
          <Button
            variant="outline"
            size="lg"
            onClick={handleSpectatorClick}
            disabled={loading}
            animate={false}
          >
            {i18nText('authRoleSpectator')}
          </Button>
        </div>
      ) : (
        // Owner PIN Mode
        <div className="flex flex-col gap-4 w-full max-w-sm">
          {randomOwnerPin ? (
            <>
              <Typography variant="body" className="text-center text-muted-foreground">
                {i18nText('authOwnerPinDescription')}
              </Typography>
              <div className="flex flex-col items-center gap-2 p-4 bg-surface-low rounded-lg border border-outline/20">
                <Typography variant="label" className="text-muted-foreground">
                  {i18nText('authOwnerPinYourPinIs')}
                </Typography>
                <Typography variant="headline" className="font-mono text-primary tracking-widest">
                  {randomOwnerPin}
                </Typography>
                <Typography variant="label" className="text-xs text-muted-foreground">
                  {i18nText('authOwnerPinUseHint')}
                </Typography>
              </div>
            </>
          ) : (
            <Typography variant="body" className="text-center text-muted-foreground">
              {i18nText('authOwnerPinEnterPin')}
            </Typography>
          )}
          <PinInput
            length={8}
            value={pin}
            onChange={handlePinChange}
            onComplete={() => {}} // Auto-submit disabled - user must click button
            disabled={loading}
            error={error}
            autoFocus
            placeholder="••••••••"
          />

          {error && (
            <Typography variant="label" className="text-red-500 text-center">
              ⚠️ {translateAuthError(error)}
            </Typography>
          )}

          <Button
            className='bg-primary text-primary-foreground hover:bg-primary/90'
            variant="primary"
            disabled={pin.length < 5 || pin.length > 8 || loading}
            onClick={handlePinSubmit}
            animate={false}
          >
            {loading ? i18nText('authVerifying') : i18nText('authEnter')}
          </Button>

          <Button
            variant="ghost"
            onClick={handleBack}
            disabled={loading}
            animate={false}
          >
            {i18nText('commonBack')}
          </Button>
        </div>
      )}
    </div>
  )
}
