import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useI18n } from '@/i18n'
import { useAuthContext } from '@/contexts/AuthContext'
import { useSocketContext } from '@/contexts/SocketContext'
import { useAuthFlow } from '@/hooks/useAuthFlow'
import { useToast } from '@/components/molecules/Toast'
import { Button } from '@/components/atoms/Button'
import { PinInput } from '@/components/atoms/PinInput'
import { Typography } from '@/components/atoms/Typography'
import { TournamentResumeModal } from '@/components/molecules/TournamentResumeModal'
import { SportDisplayRegistry } from '@/adapters/SportDisplayRegistry'
import { SPORT } from '@shared/types'
import type { Sport } from '@shared/types'
import { SocketEvents } from '@shared/events'
import logoBig from '@/assets/logo-big.png'
import { Routes } from '@/routes'

export type AuthMode = 'select' | 'owner-pin' | 'sport-select' | 'club-pin'

const registry = new SportDisplayRegistry()
const SPORT_STORAGE_KEY = 'rallyos-sport'

export function AuthPage() {
  const [pin, setPin] = useState('')
  const [mode, setMode] = useState<AuthMode>('select')
  const [randomOwnerPin, setRandomOwnerPin] = useState<string | null>(null)
  const [pendingAction, setPendingAction] = useState<'load' | 'new' | null>(null)
  // Club PIN entry state
  const [clubPin, setClubPin] = useState('')
  const [clubLoading, setClubLoading] = useState(false)
  const [clubError, setClubError] = useState<string | null>(null)
  const [clubRetryAfter, setClubRetryAfter] = useState<number | null>(null)
  // Tournament section state
  const [tournamentExpanded, setTournamentExpanded] = useState(false)
  const navigate = useNavigate()
  const { i18nText } = useI18n()
  const { login, setOwner, setTournamentToken } = useAuthContext()
  const { socket, connected } = useSocketContext()

  const { submitPin, error, loading, clearError, tournamentStatus, resolveTournament } = useAuthFlow({
    socket,
    connected,
    setOwner,
    login,
    setTournamentToken,
    onOwnerResolved: () => setMode('sport-select'),
  })

  const { addToast } = useToast()

  // Toast on auth errors
  useEffect(() => {
    if (error === 'CONNECTION_ERROR') {
      addToast('error', i18nText('toastConnectionError'));
    } else if (error === 'INVALID_OWNER_PIN') {
      addToast('error', i18nText('toastPinVerificationFailed'));
    }
  }, [error, addToast, i18nText]);

  // Fetch random owner PIN if generated by server (plug-and-play mode)
  useEffect(() => {
    fetch('/api/owner-pin')
      .then(res => res.json())
      .then(data => {
        if (data.isRandom && data.pin) {
          setRandomOwnerPin(data.pin)
        }
      })
      .catch(() => {
        // Silently fail — PIN entry still works manually
      })
  }, [])

  // Listen for CLUB_JOIN_RESULT after submitting club PIN
  useEffect(() => {
    if (!socket) return

    const handleClubJoinResult = (data: {
      success: boolean
      courtId?: string
      courtName?: string
      matchState?: unknown
      error?: string
      retryAfterSeconds?: number
    }) => {
      setClubLoading(false)
      if (data.success && data.courtId) {
        navigate(Routes.CLUB_PLAY.replace(':courtId', data.courtId))
      } else if (data.error === 'RATE_LIMITED') {
        setClubError('RATE_LIMITED')
        setClubRetryAfter(data.retryAfterSeconds ?? 60)
      } else if (data.error === 'INVALID_PIN') {
        setClubError('INVALID_PIN')
      } else {
        setClubError(data.error ?? 'UNKNOWN_ERROR')
      }
    }

    socket.on(SocketEvents.SERVER.CLUB_JOIN_RESULT, handleClubJoinResult)
    return () => {
      socket.off(SocketEvents.SERVER.CLUB_JOIN_RESULT, handleClubJoinResult)
    }
  }, [socket, navigate])

  const handleOwnerClick = () => {
    setMode('owner-pin')
    setPin('')
    clearError()
  }

  const handleRefereeClick = () => {
    login('referee')
    navigate(Routes.DASHBOARD_REFEREE)
  }

  const handleSpectatorClick = () => {
    login('viewer')
    navigate(Routes.DASHBOARD_SPECTATOR)
  }

  const handlePinChange = (value: string) => {
    setPin(value)
    if (value.length >= 5 && value.length <= 8) {
      clearError()
    }
  }

  const handlePinSubmit = () => {
    submitPin(pin)
  }

  /** Translate error codes from useAuthFlow to human-readable messages */
  const translateAuthError = (code: string): string => {
    const map: Record<string, string> = {
      INVALID_OWNER_PIN: i18nText('errorAuthInvalidPin'),
      INVALID_OWNER_PIN_FORMAT: i18nText('errorAuthInvalidPinFormat'),
      CONNECTION_ERROR: i18nText('errorAuthConnectionError'),
      VALIDATION_ERROR: i18nText('errorAuthValidationError'),
    }
    return map[code] || code
  }

  const handlePlayClick = () => {
    setMode('club-pin')
    setClubPin('')
    setClubError(null)
    setClubRetryAfter(null)
  }

  const handleAdminClick = () => {
    navigate(Routes.CLUB_ADMIN)
  }

  const handleClubPinChange = (value: string) => {
    setClubPin(value)
    if (value.length === 4 && clubError) {
      setClubError(null)
    }
  }

  const handleClubPinSubmit = () => {
    if (!socket || !connected) {
      setClubError('CONNECTION_ERROR')
      return
    }
    setClubLoading(true)
    setClubError(null)
    socket.emit(SocketEvents.CLIENT.CLUB_JOIN, { pin: clubPin })
  }

  const handleClubPinBack = () => {
    setMode('select')
    setClubPin('')
    setClubError(null)
    setClubRetryAfter(null)
  }

  const handleBack = () => {
    setMode('select')
    setPin('')
    clearError()
  }

  const handleSelectSport = (sport: Sport) => {
    localStorage.setItem(SPORT_STORAGE_KEY, sport)
    navigate(Routes.DASHBOARD_OWNER)
  }

  return (
    <div className="flex flex-col items-center justify-center min-h-dvh bg-surface gap-8 p-4">
      <div className="flex flex-col items-center gap-4">
        <img src={logoBig} alt="RallyOS" className="w-32 h-auto mb-2 rounded-[--radius-md]" />
        <Typography variant="title">
          {mode === 'select' ? i18nText('authSelectRole')
           : mode === 'sport-select' ? i18nText('configSportLabel')
           : i18nText('authEnterOwnerPin')}
        </Typography>
      </div>

      {mode === 'select' ? (
        // Selection Mode — 3-entry layout: Play, Tournament (expandable), Admin
        <div className="flex flex-col gap-4 w-full max-w-sm">
          {/* "Quiero jugar" — primary green CTA button */}
          <Button
            variant="success"
            size="xl"
            onClick={handlePlayClick}
            animate={false}
          >
            {i18nText('authClubPlay')}
          </Button>

          {/* "Torneo" — expandable section with sub-roles */}
          <div className="flex flex-col gap-2">
            <Button
              variant="secondary"
              size="lg"
              onClick={() => setTournamentExpanded(!tournamentExpanded)}
              animate={false}
            >
              <span className="flex-1 text-left">{i18nText('authTournament')}</span>
              <span>{tournamentExpanded ? '▲' : '▼'}</span>
            </Button>

            {tournamentExpanded && (
              <div className="flex flex-col gap-2 pl-4 pt-1">
                <Button
                  variant="primary"
                  size="lg"
                  onClick={handleOwnerClick}
                  disabled={loading}
                  animate={false}
                >
                  {i18nText('authRoleOwner')}
                </Button>
                <Button
                  variant="secondary"
                  size="lg"
                  onClick={handleRefereeClick}
                  disabled={loading}
                  animate={false}
                >
                  {i18nText('authRoleReferee')}
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  onClick={handleSpectatorClick}
                  disabled={loading}
                  animate={false}
                >
                  {i18nText('authRoleSpectator')}
                </Button>
              </div>
            )}
          </div>

          {/* "Administrar" — ghost/link style */}
          <Button
            variant="ghost"
            size="lg"
            onClick={handleAdminClick}
            animate={false}
          >
            {i18nText('authAdminClub')}
          </Button>
        </div>
      ) : mode === 'club-pin' ? (
        // Club PIN Entry Mode
        <div className="flex flex-col gap-4 w-full max-w-sm">
          <Typography variant="body" className="text-center text-muted-foreground">
            {i18nText('authClubPlayDesc')}
          </Typography>
          <PinInput
            length={4}
            value={clubPin}
            onChange={handleClubPinChange}
            onComplete={() => {}}
            disabled={clubLoading}
            error={clubError ?? undefined}
            autoFocus
            placeholder="••••"
          />

          {clubError === 'INVALID_PIN' && (
            <Typography variant="label" className="text-red-500 text-center">
              {i18nText('authPinErrorInvalid')}
            </Typography>
          )}
          {clubError === 'RATE_LIMITED' && (
            <Typography variant="label" className="text-red-500 text-center">
              {i18nText('authPinErrorRateLimited', { seconds: clubRetryAfter })}
            </Typography>
          )}

          <Button
            variant="primary"
            disabled={clubPin.length !== 4 || clubLoading}
            onClick={handleClubPinSubmit}
            animate={false}
          >
            {clubLoading ? (
              <span className="animate-spin inline-block h-4 w-4 border-2 border-current border-t-transparent rounded-full" />
            ) : i18nText('authPinSubmit')}
          </Button>

          <Button
            variant="ghost"
            onClick={handleClubPinBack}
            disabled={clubLoading}
            animate={false}
          >
            {i18nText('authPinBack')}
          </Button>
        </div>
      ) : mode === 'sport-select' ? (
        // Sport Selection Mode — shown after owner PIN verification
        <div className="flex flex-col gap-4 w-full max-w-sm items-center">
          <Typography variant="body" className="text-center text-muted-foreground">
            {i18nText('authSelectSportDescription')}
          </Typography>
          <div className="flex gap-3 w-full">
            {registry.getAvailableSports().map(s => (
              <Button
                key={s}
                variant="primary"
                size="lg"
                fullWidth
                icon={registry.resolve(s).icon}
                onClick={() => handleSelectSport(s)}
                animate={false}
              >
                {i18nText(registry.resolve(s).displayKey)}
              </Button>
            ))}
          </div>
        </div>
      ) : (
        // Owner PIN Mode
        <div className="flex flex-col gap-4 w-full max-w-sm">
          {randomOwnerPin ? (
            <>
              <Typography variant="body" className="text-center text-muted-foreground">
                {i18nText('authOwnerPinDescription')}
              </Typography>
              <div className="card flex flex-col items-center gap-2 p-4 bg-surface-low rounded-lg border border-outline/20">
                <Typography variant="label" className="text-muted-foreground">
                  {i18nText('authOwnerPinYourPinIs')}
                </Typography>
                <Typography variant="headline" className="font-mono text-primary tracking-widest">
                  {randomOwnerPin}
                </Typography>
                <Typography variant="label" className="text-xs text-muted-foreground">
                  {i18nText('authOwnerPinUseHint')}
                </Typography>
              </div>
            </>
          ) : (
            <Typography variant="body" className="text-center text-muted-foreground">
              {i18nText('authOwnerPinEnterPin')}
            </Typography>
          )}
          <PinInput
            length={8}
            value={pin}
            onChange={handlePinChange}
            onComplete={() => {}} // Auto-submit disabled - user must click button
            disabled={loading}
            error={error}
            autoFocus
            placeholder="••••••••"
          />

          {error && (
            <Typography variant="label" className="text-red-500 text-center">
              ⚠️ {translateAuthError(error)}
            </Typography>
          )}

          <Button
            className='bg-primary text-primary-foreground hover:bg-primary/90'
            variant="primary"
            disabled={pin.length < 5 || pin.length > 8 || loading}
            onClick={handlePinSubmit}
            animate={false}
          >
            {loading ? i18nText('authVerifying') : i18nText('authEnter')}
          </Button>

          <Button
            variant="ghost"
            onClick={handleBack}
            disabled={loading}
            animate={false}
          >
            {i18nText('commonBack')}
          </Button>
        </div>
      )}

      {/* Tournament Resume Modal — shown after owner verification if prior tournament exists */}
      <TournamentResumeModal
        isOpen={tournamentStatus.exists && !tournamentStatus.checking}
        matchCount={tournamentStatus.matchCount}
        lastSaved={tournamentStatus.lastSaved}
        onLoad={() => resolveTournament('load')}
        onNew={() => resolveTournament('new')}
      />
    </div>
  )
}
